---
layout: post
permalink: /articles/x86
tags: [x86, isa, asm, cpu]
title:  "Exploring the x86 architecture"
short_title: "The x86 architecture"
description: "Exploring the main concepts behind the x86 architecture in my perspective"
---

:author: Gustavo S. Aleixos
:page-liquid:

'''

== Overview
This article has the goal of uncovering the x86 archictecture, specially the 64-bit version, mainly focused the *way I understand them*.

Although I am basing it on Intel manuals, some mistakes could pass through me. If you find one, feel free to warn me -- my email is located at the footer of this page.

'''

== Why x86 matters

=== What's x86?
Basically, **x86** is a family (various processors) of **Instruction Set Architectures** -- You can call it **ISA**.

NOTE: An **ISA** is a `model` that will define how *software* and *hardware* will `interact` with each other, defining a **group of instructions**, **data types** and **memory access** technique.

It was developed by **Intel** in 1978, starting with the historical **8086 microprocessor**.

=== Why does it still dominate?
If you reading this article in a desktop, it's much probable your processor **ISA** being **x86-based**. That's the answer: The most of **modern personal desktops** and **servers** are totally based in x86 processor's family.

There are a bunch of ISAs that aim being modern alternatives to x86.

**ARM** is one of those. It's widely used for *mobile devices*, *embedded systems* and *servers* due to its versatility.

'''

== Versions context
As the years were passing, many improved versions of the original 8086 emerged. Considering that's a **16-bit microprocessor**, it's not dificult to imagine it would be necessary.

=== 8086
Now we know, **8086** is a 16-bit microprocessor, it is important to point its **registers** and its **buses** were limited to **16 bits**.

[IMPORTANT]
====
A **register** is a **small memory location** the processor uses to temporarily **hold data** and **instructions** for quick access during the processing. I'll detail a bit more later.

A **bus** is any **communication interface** used to **transfer data** between `components` of a system, including the processor.
====

==== 20-bit addresses
Although being a 16-bit microprocessor, **8086** could form addresses with 20 bits by using a combination of **segment registers** and **offsets**.

Each segment register is **16-bit-sized** (`2^16^ bits = 64 KiB`). This value is **4 bits left-shifted** and added to the **16-bit offset** value to compute the physical address:

[cols="1"]
|===
|`(Segment << 4) + Offset`
|===

Yep, it's kinda verbose...

=== 80386
The **first 32-bit Intel processor**, released in 1985. It was a remarkable evolution, updating the **ISA** and increasing the **clock speed**.

[TIP]
====
The **clock speed** is a measurement of how many **cycles** the processor can execute within a period. It's often measured in **Hertz** (`Hz`) and sub-variants.

For each cycle, the processor can **decode instructions** and make **operations**.
====

=== AMD Opteron
The **first 64-bit x86 processor**, released in 2003. Introduced the **64-bit version of x86** (`x86-64` or `x64`), allowing 64-bit computing.

A major expanding of the capabilities of x86 processors, enabling support for **larger amounts of memory** and **improving performance**.

NOTE: **Intel** `didn't` develop the first 64-bit x86 processor originally. It was **AMD**.

'''

== ISA modes
A modern 64-bit x86 processor is divided into three main modes:

[%header,cols="2,1,3"]
|===
|Mode
|Size
|Introduced by

|Real mode
|16 bits
|Intel 8086

|Protected mode
|32 bits
|Intel 80386

|Long mode
|64 bits
|AMD Opteron
|===

'''

== Registers
One of the most confusing aspects of x86 is that registers are not independent; they overlap.

The same physical register can be accessed at different sizes, as it's shown the following example with `RAX`.

image::/assets/img/rax.svg[opts=interactive,align="center"]

.Example
++++
{% highlight gas %}
movq $0x123400, %rax
movb $0xFF, %al

# RAX = 0x1234FF
{% endhighlight %}
++++

[NOTE]
====
The **assembly** code above pass a **literal value** to the 64-bit version to the **accumulator register**.

Modifying its **lower byte** version will also change the **physical address** of it, resulting `RAX` to be modified.

`$` is used to access a literal value.
====

=== Core registers

[%header,cols="2,1,1,1,1,1"]
|===
|Type
|64 bits
|32 bits
|16 bits
|Higher byte
|Lower byte

|Accumulator
|RAX
|EAX
|AX
|AH
|AL

|Base
|RBX
|EBX
|BX
|BH
|BL

|Counter
|RCX
|ECX
|CX
|CH
|CL

|Data
|RDX
|EDX
|DX
|DH
|DL

|Source
|RSI
|ESI
|SI
|--
|SIL

|Destination
|RDI
|EDI
|DI
|--
|DIL
|===

'''

== Instructions

Instructions are special-defined values the processor will decode.

Using **assembly**, in this case, the **GNU Assembler**, registers come together of the data size:

[%header,cols="1,1,1"]
|===
|Size
|Name
|Symbol

|64 bits
|Quadword
|`q`

|32 bits
|Long
|`l`

|16 bits
|Word
|`w`

|8 bits
|Byte
|`b`
|===

++++
{% highlight gas %}
movq %rbx, %rax
movb $8, %al
{% endhighlight %}
++++

=== Core instructions
For a quick reference, I'll list some of the most important instructions someone who's working with low level programming should know.

==== MOV
Used to **move data** from **somewhere** to **another place**.

++++
{% highlight gas %}
movq $40, %rax
movq %rax, %rbx
{% endhighlight %}
++++

==== ADD
Used to **sum** a value from a **source** to a **destination**.

++++
{% highlight gas %}
movl $50, %edi
addl $10, %edi
{% endhighlight %}
++++

==== SUB
Used to **subtract** a value from a **source** to a **destination**.

++++
{% highlight gas %}
movl $20, %edi
subl $10, %edi
{% endhighlight %}
++++

==== INC
Used to **increment** a value in **one**.

++++
{% highlight gas %}
movl $60, %edi
incl %edi
{% endhighlight %}
++++

==== DEC
Used to **decrement** a value in **one**.

++++
{% highlight gas %}
movl $10, %edi
decl %edi
{% endhighlight %}
++++
